//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransferCsvBase.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransferCsvBase.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Key,Country Name
        ///200,&quot;Argentina&quot;
        ///184,&quot;Australia&quot;
        ///104,&quot;Austria&quot;
        ///2809857,&quot;Bangladesh&quot;
        ///2809861,&quot;Algeria&quot;
        ///2809864,&quot;Belarus&quot;
        ///2809863,&quot;Azerbaijan, Republic of&quot;
        ///2809862,&quot;Angola&quot;
        ///.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Key,Indicator Name
        ///2809945,&quot;Revenue (% of GDP)&quot;
        ///2809943,&quot;Primary net lending/borrowing (also referred as primary balance) (% of GDP)&quot;
        ///2809939,&quot;Net debt (% of GDP)&quot;
        ///2922871,&quot;Expenditure (% of GDP)&quot;
        ///2922875,&quot;Gross debt (% of GDP)&quot;
        ///2809941,&quot;Net lending/borrowing (also referred as overall balance) (% of GDP)&quot;
        ///2809933,&quot;Cyclically adjusted balance (% of potential GDP)&quot;
        ///2809935,&quot;Cyclically adjusted primary balance (% of potential GDP)&quot;
        ///.
        /// </summary>
        internal static string Indicator {
            get {
                return ResourceManager.GetString("Indicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SerieKey,Time,Value
        ///1,1993,22.68463728
        ///1,1994,22.36255856
        ///1,1995,21.41253242
        ///1,1996,20.4931889
        ///1,1997,21.39417724
        ///1,1998,21.96012982
        ///1,1999,22.42590983
        ///1,2000,22.678129
        ///1,2001,21.79250679
        ///1,2002,20.47768613
        ///1,2003,23.88175555
        ///1,2004,26.54538589
        ///1,2005,26.60076046
        ///1,2006,26.91507626
        ///1,2007,28.04545114
        ///1,2008,29.29168863
        ///1,2009,30.18885129
        ///1,2010,30.44878907
        ///1,2011,30.59037321
        ///1,2012,32.05793386
        ///1,2013,32.61977037
        ///1,2014,32.44011106
        ///1,2015,33.97370411
        ///1,2016,32.45858337
        ///1,2017,32.3475 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Observables {
            get {
                return ResourceManager.GetString("Observables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Key,Country,Indicator,Comment
        ///1,200,2809945,
        ///2,200,2809943,
        ///3,184,2809943,
        ///4,104,2809943,
        ///5,184,2809939,
        ///6,104,2809939,
        ///7,200,2922871,
        ///8,184,2922871,
        ///9,104,2922871,
        ///10,200,2922875,
        ///11,184,2922875,
        ///12,104,2922875,
        ///13,200,2809941,
        ///14,184,2809941,My Comment
        ///15,104,2809941,
        ///16,184,2809945,
        ///17,104,2809945,
        ///18,200,2809933,
        ///19,200,2809935,
        ///20,184,2809935,
        ///21,104,2809935,
        ///22,184,2809933,
        ///23,104,2809933,
        ///24,2809857,2809945,
        ///25,2809857,2809941,
        ///26,2809857,2922875,
        ///27,2809857,2922871,
        ///28,28 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Series {
            get {
                return ResourceManager.GetString("Series", resourceCulture);
            }
        }
    }
}
